// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// BluePressedHandlerFunc turns a function with the right signature into a blue pressed handler
type BluePressedHandlerFunc func(BluePressedParams) middleware.Responder

// Handle executing the request and returning a response
func (fn BluePressedHandlerFunc) Handle(params BluePressedParams) middleware.Responder {
	return fn(params)
}

// BluePressedHandler interface for that can handle valid blue pressed params
type BluePressedHandler interface {
	Handle(BluePressedParams) middleware.Responder
}

// NewBluePressed creates a new http.Handler for the blue pressed operation
func NewBluePressed(ctx *middleware.Context, handler BluePressedHandler) *BluePressed {
	return &BluePressed{Context: ctx, Handler: handler}
}

/*BluePressed swagger:route POST /api/v1/blue bluePressed

BluePressed blue pressed API

*/
type BluePressed struct {
	Context *middleware.Context
	Handler BluePressedHandler
}

func (o *BluePressed) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewBluePressedParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// BluePressedOKBody blue pressed o k body
//
// swagger:model BluePressedOKBody
type BluePressedOKBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this blue pressed o k body
func (o *BluePressedOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *BluePressedOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *BluePressedOKBody) UnmarshalBinary(b []byte) error {
	var res BluePressedOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
