// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// BluePressedOKCode is the HTTP code returned for type BluePressedOK
const BluePressedOKCode int = 200

/*BluePressedOK blue pressed

swagger:response bluePressedOK
*/
type BluePressedOK struct {

	/*
	  In: Body
	*/
	Payload *BluePressedOKBody `json:"body,omitempty"`
}

// NewBluePressedOK creates BluePressedOK with default headers values
func NewBluePressedOK() *BluePressedOK {

	return &BluePressedOK{}
}

// WithPayload adds the payload to the blue pressed o k response
func (o *BluePressedOK) WithPayload(payload *BluePressedOKBody) *BluePressedOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the blue pressed o k response
func (o *BluePressedOK) SetPayload(payload *BluePressedOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *BluePressedOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
