// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// OrangePressedOKCode is the HTTP code returned for type OrangePressedOK
const OrangePressedOKCode int = 200

/*OrangePressedOK orange pressed

swagger:response orangePressedOK
*/
type OrangePressedOK struct {

	/*
	  In: Body
	*/
	Payload *OrangePressedOKBody `json:"body,omitempty"`
}

// NewOrangePressedOK creates OrangePressedOK with default headers values
func NewOrangePressedOK() *OrangePressedOK {

	return &OrangePressedOK{}
}

// WithPayload adds the payload to the orange pressed o k response
func (o *OrangePressedOK) WithPayload(payload *OrangePressedOKBody) *OrangePressedOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the orange pressed o k response
func (o *OrangePressedOK) SetPayload(payload *OrangePressedOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *OrangePressedOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
