// Code generated by go-swagger; DO NOT EDIT.

// Package restapi clpsec app
//
//  Application used for clpsec
//  Schemes:
//    http
//  Host: clpsec
//  BasePath: /
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
