// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Gql gql
//
// swagger:model gql
type Gql struct {

	// gql field
	// Required: true
	GqlField *string `json:"gqlField"`
}

// Validate validates this gql
func (m *Gql) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateGqlField(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Gql) validateGqlField(formats strfmt.Registry) error {

	if err := validate.Required("gqlField", "body", m.GqlField); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Gql) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Gql) UnmarshalBinary(b []byte) error {
	var res Gql
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
